name: CI

on: push

jobs:
  build-firmware:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python with cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python requirements
        run: pip install -r ./scripts/requirements.txt

      - name: Create cache key for platformio.ini from platform_packages and lib_deps
        run: |
          echo "PLATFORM_IO_KEY=$(cat platformio.ini | grep -oPz '(?:lib_deps|platform_packages) =\\s*?(?:(?:\\t| )+.*\\n?)*' | md5sum | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ env.PLATFORM_IO_KEY }}

      - name: Build the firmware
        run: pio run -e m5paper

      - name: Store firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/m5paper/firmware.bin

  build-file-system:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python with cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python requirements
        run: pip install -r ./scripts/requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: setup-frontend/package-lock.json

      - name: Build frontend
        run: python ./scripts/setup.py frontend

      - name: Store file system artifact
        uses: actions/upload-artifact@v3
        with:
          name: file-system
          path: data
          
  deploy-beta:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-firmware, build-file-system]
    uses: ./.github/workflows/deploy.yaml
    with:
      channel: beta
    secrets: inherit
  

  deploy-stable:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-firmware, build-file-system, deploy-beta]
    uses: ./.github/workflows/deploy.yaml
    with:
      channel: stable
    secrets: inherit