name: CI

on: 
  push:
    branches: [master]

jobs:
  build-firmware:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python with cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python requirements
        run: pip install -r ./scripts/requirements.txt

      - name: Build the firmware
        run: pio run -e m5paper

      - name: Store firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/m5paper/firmware.bin

  build-file-system:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python with cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python requirements
        run: pip install -r ./scripts/requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: webPortalFrontend/package-lock.json

      - name: Build frontend
        run: python ./scripts/setup.py frontend

      - name: Store file system artifact
        uses: actions/upload-artifact@v3
        with:
          name: file-system
          path: data
          
  deploy-beta:
    needs: [build-firmware, build-file-system, deploy-beta]
    uses: ./deploy.yaml
    with:
      channel: beta
    secrets: inherit
  

  deploy-stable:
    needs: [build-firmware, build-file-system, deploy-beta]
    uses: ./deploy.yaml
    with:
      channel: stable
    secrets: inherit