name: Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download firmware artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: ./artifacts

      - name: Download file system artifact
        uses: actions/download-artifact@v3
        with:
          name: file-system
          path: ./artifacts/data

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - run: mkdir ./v${{ steps.tag.outputs.tag }}

      - name: Move firmware
        run: mv ./artifacts/firmware.bin ./v${{ steps.tag.outputs.tag }}/firmware.bin

      - name: Compress file system
        working-directory: ./artifacts/data
        run: tar -czvf ../../v${{ steps.tag.outputs.tag }}/file-system.tar.gz ./*

      - name: Make LATEST_VERSION file
        run: echo -n ${{ steps.tag.outputs.tag }} > LATEST_VERSION

      - name: Authorize account for Google Storage
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload to Google Storage bucket
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "./v${{ steps.tag.outputs.tag }}"
          destination: "no-booking-binaries"

      - name: Update LATEST_VERSION in Google Storage bucket
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "./LATEST_VERSION"
          destination: "no-booking-binaries"
          headers: |-
            content-type: text/plain
