name: Deploy

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.channel }}
    steps:
      - uses: actions/checkout@v3

      - name: Check that channel is either "beta" or "stable"
        run:  |
          if [[ "${{ inputs.channel }}" != "beta" && "${{ inputs.channel }}" != "stable" ]]; then
            echo "Channel must be either 'beta' or 'stable'"
            exit 1
          fi
      
      - name: Set deploy folder
        run: |
          if [[ "${{ inputs.channel }}" == "beta" ]]; then
            echo "DEPLOY_FOLDER=beta/" >> $GITHUB_ENV
          else
            echo "DEPLOY_FOLDER=" >> $GITHUB_ENV
          fi

      - name: Get version numbers from platformio.ini
        run: |
          export MAJOR="$(grep -oP 'DVERSION_MAJOR=\K\w+$' platformio.ini)"
          export MINOR="$(grep -oP 'DVERSION_MINOR=\K\w+$' platformio.ini)"
          export PATCH="$(grep -oP 'DVERSION_PATCH=\K\w+$' platformio.ini)"
          export VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo VERSION="${VERSION}" >> $GITHUB_ENV
      
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Verify that platformio.ini defines the same version as the tag
        run: |
          if [[ "${{ env.VERSION }}" != "${{ steps.tag.outputs.tag }}" ]]; then
            echo "Version in platformio.ini (${{ env.VERSION }}) does not match tag (${{ steps.tag.outputs.tag }})";
            exit 1;
          fi
      
      - name: Verify that this version is not already deployed
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://storage.googleapis.com/no-booking-binaries/${{ env.DEPLOY_FOLDER }}v${{ env.VERSION }}/firmware.bin | grep -q 404

      - name: Download firmware artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: ./artifacts

      - name: Download file system artifact
        uses: actions/download-artifact@v3
        with:
          name: file-system
          path: ./artifacts/data
  
      - name: Compress file system
        working-directory: ./artifacts/data
        run: tar czvf ../file-system.tar.gz * && cd .. && rm -r ./data

      - name: Make current-version file
        run: echo -n ${{ env.VERSION }} > current-version

      - name: Authorize account for Google Storage
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload to Google Storage bucket
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "./artifacts"
          destination: "no-booking-binaries/${{ env.DEPLOY_FOLDER }}v${{ env.VERSION }}"
          parent: false

      - name: Update current-version in Google Storage bucket
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "./current-version"
          destination: "no-booking-binaries/${{ env.DEPLOY_FOLDER }}"
          headers: |-
            content-type: text/plain
            cache-control: no-cache